title: auliaaaz
description: My Portfolio Website
theme: just-the-docs

url: https://auliaaaz.github.io

# Search bar text
search:
  placeholder: Search auliaaaz

aux_links: false

# Enable navigation
nav_enabled: true

# Set default layouts for docs directory
defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"
