title: auliaaaz
description: My Portfolio Website
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

url: https://auliaaaz.github.io

# Search bar text
search:
  placeholder: Search auliaaaz

aux_links: false
